[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.api]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
startCommand = "apache2-foreground"

[services.swagger]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.swagger"
