name: CI Backend

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Instalar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Instalar dependencias
      run: composer install || true

    - name: Ejecutar tests
      run: ./vendor/bin/phpunit || true
